@ApiServer_HostAddress = https://localhost:7093

POST {{ApiServer_HostAddress}}/user/register
Content-Type: application/json

{
  "id": "test",
  "name": "test",
  "password": "test"
}

###

POST {{ApiServer_HostAddress}}/user/password-generate?pasword=test

###

POST {{ApiServer_HostAddress}}/user/Login
Content-Type: application/json

{
  "id": "test",
  "password": "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"
}

###

POST {{ApiServer_HostAddress}}/user/logout

###
